{{- if and .Values.result.enabled .Values.result.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "voting-app.fullname" . }}-result
  labels:
    {{- include "voting-app.componentLabels" (dict "component" "result" "Values" .Values "Release" .Release "Chart" .Chart) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "voting-app.fullname" . }}-result
  minReplicas: {{ .Values.result.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.result.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.result.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.result.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.result.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.result.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}

