{{- if and .Values.vote.enabled .Values.vote.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "voting-app.fullname" . }}-vote
  labels:
    {{- include "voting-app.componentLabels" (dict "component" "vote" "Values" .Values "Release" .Release "Chart" .Chart) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "voting-app.fullname" . }}-vote
  minReplicas: {{ .Values.vote.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.vote.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.vote.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.vote.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.vote.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.vote.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}

